import { chromium } from "playwright";
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: { width: 390, height: 844 }, isMobile: true });
const p = await ctx.newPage();
const errs = [];
p.on("pageerror", (e) => errs.push(e.message));
await p.goto("http://localhost:5173/", { waitUntil: "networkidle" });
await p.locator("#calculadora").scrollIntoViewIfNeeded();
await p.waitForTimeout(400);
const add = p.getByRole("button", { name: /^Agregar / });
const n = await add.count();
for (let i = 0; i < n; i++) await add.nth(i).click();
await p.waitForTimeout(500);
await p.getByRole("button", { name: /Mi paquete/ }).click();
await p.waitForTimeout(900);
const wa = p.getByRole("button", { name: /Finalizar pedido por WhatsApp/ });
const box = await wa.boundingBox();
console.log("Drawer mobile con", n, "productos:");
console.log("  WhatsApp visible:", await wa.isVisible());
console.log("  Dentro de viewport (", box ? Math.round(box.y + box.height) : "?", "≤ 844):", box ? box.y + box.height <= 845 : "?");
await p.screenshot({ path: "scripts/_mobile-lleno.png" });
await b.close();
console.log("Errores:", errs.length ? errs : "0");
